### ISSUE TITLE
ConnectionResetError('Connection lost')

### ISSUE THREAD

**Issue by Schmandre** [rhasspy/wyoming-faster-whisper#16]
Hello,

Iam using home assistant as docker version and have installed whisper, piper and openwakeword.

Today, after I tried to use this with my analog phone, I was wondering why nothing works. In Home Assistant "Speech to text" is loading endless and in docker compose logs I can see an ConnectionResetError('Connection lost')

Here is an Log output:
```
whisper       | INFO:__main__:Downloading FasterWhisperModel.BASE_INT8 to /data
whisper       | INFO:__main__:Ready
piper         | INFO:__main__:Ready
whisper       | INFO:wyoming_faster_whisper.handler:
whisper       | ERROR:asyncio:Task exception was never retrieved
whisper       | future: <Task finished name='Task-11' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.9/dist-packages/wyoming/server.py:28> exception=ConnectionResetError('Connection lost')>
whisper       | Traceback (most recent call last):
whisper       |   File "/usr/local/lib/python3.9/dist-packages/wyoming/server.py", line 35, in run
whisper       |     if not (await self.handle_event(event)):
whisper       |   File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/handler.py", line 78, in handle_event
whisper       |     await self.write_event(Transcript(text=text).event())
whisper       |   File "/usr/local/lib/python3.9/dist-packages/wyoming/server.py", line 26, in write_event
whisper       |     await async_write_event(event, self.writer)
whisper       |   File "/usr/local/lib/python3.9/dist-packages/wyoming/event.py", line 114, in async_write_event
whisper       |     await writer.drain()
whisper       |   File "/usr/lib/python3.9/asyncio/streams.py", line 387, in drain
whisper       |     await self._protocol._drain_helper()
whisper       |   File "/usr/lib/python3.9/asyncio/streams.py", line 190, in _drain_helper
whisper       |     raise ConnectionResetError('Connection lost')
whisper       | ConnectionResetError: Connection lost
^Ccanceled
```

I didnt changed anything less the phone. I tested first with atom echo => works fine, but now everything is rip :´(

```
version: "3"
services:
  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    command: --model base-int8 --language de
    volumes:
      - ./whisper-data:/data
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    ports:
      - 10300:10300

  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    command: --voice de_DE-thorsten_emotional-medium
    volumes:
      - ./piper-data:/data
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    ports:
      - 10200:10200

  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    volumes:
      - ./openwakeword-data:/data
      - ./openwakeword-wakeword:/custom
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    command: --preload-model 'ok_nabu' --custom-model-dir /custom
    restart: unless-stopped
    ports:
      - 10400:10400/udp
      - 10400:10400/tcp
```

Thank you all in advanced

A small edit cause it could be important (I think ^^) the Home Assistant, Assistant Log

```
stage: done
run:
  pipeline: 01hj0r5dsj486zmkxmn7p5qy2k
  language: de
events:
  - type: run-start
    data:
      pipeline: 01hj0r5dsj486zmkxmn7p5qy2k
      language: de
    timestamp: "2024-01-12T05:43:28.121428+00:00"
  - type: stt-start
    data:
      engine: stt.faster_whisper
      metadata:
        language: de
        format: wav
        codec: pcm
        bit_rate: 16
        sample_rate: 16000
        channel: 1
    timestamp: "2024-01-12T05:43:28.122022+00:00"
  - type: stt-vad-start
    data:
      timestamp: 170
    timestamp: "2024-01-12T05:43:28.140268+00:00"
  - type: stt-vad-end
    data:
      timestamp: 535
    timestamp: "2024-01-12T05:43:28.170798+00:00"
  - type: run-end
    data: null
    timestamp: "2024-01-12T05:43:58.116595+00:00"
stt:
  engine: stt.faster_whisper
  metadata:
    language: de
    format: wav
    codec: pcm
    bit_rate: 16
    sample_rate: 16000
    channel: 1
  done: false

```
