### ISSUE TITLE
Issue when deploying Wyoming container

### ISSUE THREAD

**Issue by Digitalpeer1** [rhasspy/wyoming-faster-whisper#37]
I am trying to run Wyoming whisper in a docker container because I am running HA core and add-ons do not work when I try to deploy the container I get this error: 

`2024-11-20T22:45:25.473858870Z huggingface_hub.errors.LocalEntryNotFoundError: Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input.` 

my yaml is: 

`version: "3"
services:
  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    command: --model medium-int8 --language en
    volumes:
      - ./whisper-data:/data
    environment:
      - TZ=US/Eastern
      - local_files_only=False
      - HF_HUB_CACHE=/tmp
    restart: unless-stopped
    ports:
      - 10300:10300

  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    command: --voice en_US-lessac-medium
    volumes:
      - ./piper-data:/data
    environment:
      - TZ=US/Eastern
      - local_files_only=False
      - HF_HUB_CACHE=/tmp
    restart: unless-stopped
    ports:
      - 10200:10200`

**Comment by florian-asche** [comment]
Use this, thank me later:
```
---
networks:
  traefik:                # alias
    external: true        # use pre-existing networks
    name: traefik         # global name over multiple stacks
  default:                # default network for this project
  mynet:                  # ADMIN NET IP
    external: true


services:
  # Piper = Text zu Sprache !OK!
  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    restart: unless-stopped
    #ports:
    #  - '10200:10200'
    volumes:
      - 'piper_data:/data'
    command: --voice de_DE-kerstin-low --max-piper-procs 6 --update-voices
    #--speaker 0 --length_scale 1.0 --noise_scale 0.667 --noise_w 0.333 --max_piper_procs 1 --debug_logging false --update voices true
    networks:
      - traefik
      - default
    environment:
      - TZ=Europe/Berlin

  # Whisper = Sprache zu Text
  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    restart: unless-stopped
    #ports:
    #  - '10300:10300'
    volumes:
      - 'whisper_data:/data'
    #entrypoint: python3
    #command: -m wyoming_faster_whisper --uri tcp://0.0.0.0:10300 --model tiny-int8 --beam-size 1 --language de --data-dir /data --download-dir /data
    #command: "--model base-int8 --language de"
    #command: "--model small-int8 --language de --beam-size 1"
    # small 7 gut
    command: '--initial-prompt "str?" --model small --data-dir "/data" --language de --beam-size 7'
    networks:
      - traefik
      - default
    environment:
      - TZ=Europe/Berlin

  # Wake Word Erkennung
  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    restart: unless-stopped
    #user: 1001:1001
    networks:
      - traefik
      - default
    #ports:
    #  - '10400:10400'
    volumes:
      - wakeword_data:/data
      - wakeword_custom:/custom
      - /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    command: "--preload-model 'hey_jarvis' --custom-model-dir /custom --threshold 0.5 --trigger-level 1"


volumes:
  whisper_data:
  piper_data:
  rhasspy_profiles:
  wakeword_data:
  wakeword_custom:

```
